POST http://localhost:3003/api/users
Content-Type: application/json

{ "username": "CreateUser2","name": "Peppiina", "password":"secret"}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{ "username": "CreateUser2","name": "Peppiina", "password":"secret"}