DELETE http://localhost:3003/api/blogs/6030f558f4e17802adda3595
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNyZWF0ZVVzZXIyIiwiaWQiOiI2MDMwZWE5MjlkNzI1ZWVjNzg4YjA5Y2YiLCJpYXQiOjE2MTU0Nzk4OTYsImV4cCI6MTYxNTQ4MzQ5Nn0.BuvKiYzzvQMBaYsCWpEkxSONH-Ud7mlNgJClH_hmNq4
